"""Streamlit dashboard for the workflow risk decision-support system.

*** All underlying data is synthetic. *** It is generated by
scripts/generate_demo_data.py and does not represent a real business.
Model performance figures in the Model Performance tab describe the
classifier's behavior on this synthetic dataset only -- not real-world
business performance.
"""

from __future__ import annotations

import json
import logging

import pandas as pd
import streamlit as st

from workflow_ai.config import (
    ALERTS_OUTPUT_PATH,
    DATA_RAW_DIR,
    KPI_SUMMARY_OUTPUT_PATH,
    MODEL_METADATA_PATH,
    MODEL_PATH,
    PREDICTIONS_OUTPUT_PATH,
    RECOMMENDATIONS_OUTPUT_PATH,
    RISK_LABELS,
)
from workflow_ai.data_loader import load_workflow_data
from workflow_ai.service import load_and_validate_workflow_data, run_pipeline, save_outputs

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger(__name__)

st.set_page_config(page_title="Workflow Risk Dashboard", layout="wide")

_OUTPUT_PATHS = (
    PREDICTIONS_OUTPUT_PATH,
    ALERTS_OUTPUT_PATH,
    KPI_SUMMARY_OUTPUT_PATH,
    RECOMMENDATIONS_OUTPUT_PATH,
)


def _outputs_freshness_signature() -> float:
    """Latest mtime across the 4 output files (and model metadata), or -1.0 if any is missing.

    Used as a cache key for _load_outputs so the cache invalidates
    whenever the underlying files actually change on disk -- including
    across a plain browser reload or a different session -- rather than
    relying on in-session state that resets on reload.
    """
    paths = (*_OUTPUT_PATHS, MODEL_METADATA_PATH)
    if any(not path.exists() for path in paths):
        return -1.0
    return max(path.stat().st_mtime for path in paths)


@st.cache_data(show_spinner=False)
def _load_outputs(_freshness_signature: float) -> dict | None:
    """Load the 4 pipeline output files plus raw workflow data and model metadata.

    Returns None if any pipeline output file is missing (pipeline has
    never been run). _freshness_signature (see _outputs_freshness_signature)
    is the cache key: Streamlit's cache_data reruns this function whenever
    it changes, i.e. whenever any output file's mtime changes.
    """
    if any(not path.exists() for path in _OUTPUT_PATHS):
        return None

    predictions_df = pd.read_csv(PREDICTIONS_OUTPUT_PATH)
    alerts_df = pd.read_csv(ALERTS_OUTPUT_PATH)
    recommendations_df = pd.read_csv(RECOMMENDATIONS_OUTPUT_PATH)
    with KPI_SUMMARY_OUTPUT_PATH.open(encoding="utf-8") as handle:
        kpi_summary = json.load(handle)

    raw_path = DATA_RAW_DIR / "workflows.csv"
    workflows_df = load_workflow_data(raw_path) if raw_path.exists() else None

    model_metadata = None
    if MODEL_METADATA_PATH.exists():
        with MODEL_METADATA_PATH.open(encoding="utf-8") as handle:
            model_metadata = json.load(handle)

    return {
        "predictions": predictions_df,
        "alerts": alerts_df,
        "recommendations": recommendations_df,
        "kpi_summary": kpi_summary,
        "workflows": workflows_df,
        "model_metadata": model_metadata,
    }


def _render_sidebar_rerun_controls() -> None:
    st.sidebar.header("Pipeline")
    train_if_missing = st.sidebar.checkbox(
        "Train model if missing",
        value=False,
        help="Opt-in: trains and persists a new model before running if none exists at models/workflow_risk_model.joblib.",
    )
    if st.sidebar.button("Re-run pipeline", type="primary"):
        raw_path = DATA_RAW_DIR / "workflows.csv"
        try:
            with st.spinner("Running pipeline..."):
                df = load_and_validate_workflow_data(raw_path)
                result = run_pipeline(df, train_if_missing=train_if_missing, model_path=MODEL_PATH)
                save_outputs(result)
            st.sidebar.success(
                f"Pipeline complete: {len(result.predictions)} predictions, {len(result.alerts)} alerts."
            )
            st.rerun()
        except FileNotFoundError as error:
            st.sidebar.error(f"No trained model available: {error}")
        except ValueError as error:
            st.sidebar.error(f"Workflow data failed validation:\n{error}")


def _apply_filters(predictions_df: pd.DataFrame, workflows_df: pd.DataFrame | None) -> pd.DataFrame:
    merged = predictions_df
    if workflows_df is not None:
        merged = predictions_df.merge(
            workflows_df[["workflow_id", "department", "status", "priority"]],
            on="workflow_id",
            how="left",
        )

    st.sidebar.header("Filters")
    risk_filter = st.sidebar.multiselect(
        "Risk level", options=list(RISK_LABELS), default=list(RISK_LABELS)
    )
    filtered = merged[merged["predicted_risk"].isin(risk_filter)]

    for column, label in (
        ("department", "Department"),
        ("status", "Status"),
        ("priority", "Priority"),
    ):
        if column not in merged.columns:
            continue
        options = sorted(merged[column].dropna().unique())
        selected = st.sidebar.multiselect(label, options=options, default=options)
        filtered = filtered[filtered[column].isin(selected)]

    return filtered


def _render_executive_overview(kpi_summary: dict, filtered_predictions: pd.DataFrame) -> None:
    st.caption(
        "Rule-based KPIs (deterministic) alongside ML-derived risk counts, for the current filter selection."
    )

    volume = kpi_summary["volume"]
    sla = kpi_summary["sla"]
    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Total workflows (unfiltered)", volume["total_workflows"])
    col2.metric("SLA breach rate", f"{sla['sla_breach_rate']:.1%}")
    col3.metric("Filtered workflows shown", len(filtered_predictions))
    high_risk_count = int((filtered_predictions["predicted_risk"] == "high").sum())
    col4.metric("High-risk workflows (filtered)", high_risk_count)

    st.subheader("ML-derived: predicted risk distribution (filtered)")
    risk_counts = (
        filtered_predictions["predicted_risk"].value_counts().reindex(RISK_LABELS, fill_value=0)
    )
    st.bar_chart(risk_counts)


def _render_risk_monitor(filtered_predictions: pd.DataFrame) -> None:
    st.caption(
        "ML-derived: Random Forest predicted risk per workflow, with deterministic rule-based risk factors."
    )
    display_columns = [
        column
        for column in (
            "workflow_id",
            "department",
            "status",
            "priority",
            "predicted_risk",
            "risk_probability_low",
            "risk_probability_medium",
            "risk_probability_high",
            "risk_factors",
        )
        if column in filtered_predictions.columns
    ]
    sort_column = (
        "risk_probability_high"
        if "risk_probability_high" in filtered_predictions.columns
        else "workflow_id"
    )
    st.dataframe(
        filtered_predictions[display_columns].sort_values(sort_column, ascending=False),
        use_container_width=True,
        hide_index=True,
    )


def _render_kpi_analysis(kpi_summary: dict) -> None:
    st.caption(
        "Rule-based, deterministic KPIs computed independently of the ML model. Not filtered by sidebar selections."
    )

    st.subheader("Volume")
    volume = kpi_summary["volume"]
    st.write(f"Total workflows: {volume['total_workflows']}")
    vol_col1, vol_col2, vol_col3 = st.columns(3)
    vol_col1.bar_chart(pd.Series(volume["by_status"], name="Workflows"))
    vol_col2.bar_chart(pd.Series(volume["by_department"], name="Workflows"))
    vol_col3.bar_chart(pd.Series(volume["by_priority"], name="Workflows"))

    st.subheader("SLA")
    sla = kpi_summary["sla"]
    sla_col1, sla_col2, sla_col3 = st.columns(3)
    sla_col1.metric("Avg SLA utilization", f"{sla['avg_sla_utilization']:.1%}")
    sla_col2.metric(
        "Breach rate", f"{sla['sla_breach_rate']:.1%}", f"{sla['sla_breach_count']} workflows"
    )
    sla_col3.metric(
        "Approaching-SLA rate",
        f"{sla['sla_approaching_rate']:.1%}",
        f"{sla['sla_approaching_count']} workflows",
    )

    st.subheader("Efficiency")
    efficiency = kpi_summary["efficiency"]
    eff_col1, eff_col2, eff_col3 = st.columns(3)
    eff_col1.metric("Avg manual step ratio", f"{efficiency['avg_manual_step_ratio']:.1%}")
    eff_col2.metric("Avg automation score", f"{efficiency['avg_automation_score']:.1%}")
    eff_col3.metric("Avg completion rate", f"{efficiency['avg_completion_rate']:.1%}")

    st.subheader("By department")
    st.dataframe(
        pd.DataFrame(kpi_summary["by_department"]), use_container_width=True, hide_index=True
    )


def _render_alerts(filtered_alerts: pd.DataFrame) -> None:
    st.caption(
        "Rule-based: deterministic alerts generated by the rules engine's thresholds. No ML output here."
    )
    if filtered_alerts.empty:
        st.info("No alerts for the current filter selection.")
        return

    severity_counts = filtered_alerts["severity"].value_counts()
    st.bar_chart(severity_counts)
    st.dataframe(
        filtered_alerts.sort_values("severity"),
        use_container_width=True,
        hide_index=True,
    )


def _render_recommendations(filtered_recommendations: pd.DataFrame) -> None:
    st.caption(
        "Rule-based: recommendations tied to an observed rules-engine signal. No ML output here."
    )
    if filtered_recommendations.empty:
        st.info("No recommendations for the current filter selection.")
        return

    category_counts = filtered_recommendations["category"].value_counts()
    st.bar_chart(category_counts)
    st.dataframe(filtered_recommendations, use_container_width=True, hide_index=True)


def _render_model_performance(model_metadata: dict | None) -> None:
    st.warning(
        "This tab describes the Random Forest classifier's performance on the synthetic demo "
        "dataset only. It is not a measure of real-world business performance."
    )
    if model_metadata is None:
        st.info("No model metadata found. Run scripts/train_model.py to train a model.")
        return

    col1, col2, col3 = st.columns(3)
    col1.metric("Model type", model_metadata["model_type"])
    col2.metric("Trained at (UTC)", model_metadata["trained_at"])
    col3.metric("Random seed", model_metadata["random_state"])

    test_metrics = model_metadata["test_metrics"]
    st.subheader("Primary model (random_forest) test metrics")
    metric_col1, metric_col2, metric_col3 = st.columns(3)
    metric_col1.metric("Accuracy", f"{test_metrics['accuracy']:.1%}")
    metric_col2.metric("F1 (macro)", f"{test_metrics['f1_macro']:.3f}")
    metric_col3.metric("F1 (weighted)", f"{test_metrics['f1_weighted']:.3f}")

    st.write("Confusion matrix (rows = actual, columns = predicted):")
    labels = test_metrics["labels"]
    st.dataframe(pd.DataFrame(test_metrics["confusion_matrix"], index=labels, columns=labels))

    st.subheader("Baseline comparison")
    baseline_rows = [
        {
            "model": name,
            "accuracy": metrics["accuracy"],
            "f1_macro": metrics["f1_macro"],
            "f1_weighted": metrics["f1_weighted"],
        }
        for name, metrics in model_metadata["baseline_comparison"].items()
    ]
    baseline_rows.append(
        {
            "model": "random_forest (primary)",
            "accuracy": test_metrics["accuracy"],
            "f1_macro": test_metrics["f1_macro"],
            "f1_weighted": test_metrics["f1_weighted"],
        }
    )
    st.dataframe(pd.DataFrame(baseline_rows), use_container_width=True, hide_index=True)

    st.caption(model_metadata["data_note"])


def main() -> None:
    """Streamlit entry point."""
    st.title("Workflow Risk Decision-Support Dashboard")
    st.caption(
        "All data shown is synthetic, generated by scripts/generate_demo_data.py for demonstration "
        "purposes. It does not represent a real business."
    )

    _render_sidebar_rerun_controls()

    data = _load_outputs(_outputs_freshness_signature())
    if data is None:
        st.warning(
            "No pipeline outputs found yet. Click **Re-run pipeline** in the sidebar to generate "
            "predictions, alerts, KPIs, and recommendations."
        )
        return

    filtered_predictions = _apply_filters(data["predictions"], data["workflows"])
    filtered_workflow_ids = set(filtered_predictions["workflow_id"])
    filtered_alerts = data["alerts"][data["alerts"]["workflow_id"].isin(filtered_workflow_ids)]
    filtered_recommendations = data["recommendations"][
        data["recommendations"]["workflow_id"].isin(filtered_workflow_ids)
    ]

    tabs = st.tabs(
        [
            "Executive Overview",
            "Workflow Risk Monitor",
            "KPI Analysis",
            "Alerts",
            "Recommendations",
            "Model Performance",
        ]
    )
    with tabs[0]:
        _render_executive_overview(data["kpi_summary"], filtered_predictions)
    with tabs[1]:
        _render_risk_monitor(filtered_predictions)
    with tabs[2]:
        _render_kpi_analysis(data["kpi_summary"])
    with tabs[3]:
        _render_alerts(filtered_alerts)
    with tabs[4]:
        _render_recommendations(filtered_recommendations)
    with tabs[5]:
        _render_model_performance(data["model_metadata"])


if __name__ == "__main__":
    main()
